apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: shopware
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: shopware
  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.hpa.cpuAverageUtilization }}
    - type: Resource
      resource:
        name: memory
        targetAverageValue: {{ .Values.hpa.memoryTargetAverageValue }}
