apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: shopware
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: shopware
  minReplicas: 1
  maxReplicas: 20
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 65
    - type: Resource
      resource:
        name: memory
        targetAverageValue: "100Mi"
