kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "shopware.name" . | quote }}
  labels: {{- include "shopware.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  {{ include "shopware.storageClass" . }}