apiVersion: v1
kind: Service
metadata:
  name: shopware
spec:
  type: { { .Values.service.type } }
  ports:
    - name: shopware
      port: { { .Values.service.port } }
      protocol: TCP
      targetPort: { { .Values.service.targetPort } }
  selector:
    app: shopware
