apiVersion: v1
kind: Secret
metadata:
  name: {{ include "shopware.secretName" . }}
  labels: {{- include "shopware.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.shopware.jwtPassphrase }}
  jwt-passphrase: {{ .Values.shopware.jwtPassphrase | b64enc | quote }}
  {{- else }}
  jwt-passphrase: {{ randAlphaNum 16 | b64enc | quote }}
  {{- end }}
  {{- if .Values.shopware.adminPassword }}
  admin-password: {{ .Values.shopware.adminPassword | b64enc | quote }}
  {{- else }}
  admin-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  {{- if .Values.shopware.appSecret }}
  app-secret: {{ .Values.shopware.appSecret | b64enc | quote }}
  {{- else }}
  app-secret: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}