image:
  registry: docker.io
  repository: shopware/production
  tag: 6.1.3
  pullPolicy: IfNotPresent

labels:
  env: "dev"
  cluster: "dev"

service:
  port: 80
  targetPort: 8000
  type: LoadBalancer

resources:
  limits:
    cpu: 650m
    memory: 2000Mi
  requests:
    memory: 1000Mi
    cpu: 500m
