image:
  repository: shopware/production
  tag: 6.1.3
  pullPolicy: IfNotPresent

labels:
  env: "dev"
  cluster: "dev"

service:
  port: 80
  targetPort: 8000
  type: LoadBalancer

resources:
  limits:
    cpu: 2000m
    memory: 2Gi
  requests:
    memory: 1Gi
    cpu: 1000m

hpa:
  minReplicas: 3
  maxReplicas: 6
  cpuAverageUtilization: 65
  memoryTargetAverageValue: 1000Mi

shopware:
  storefrontURL: "http://shopware.local"
  jwtPassphrase: "REPLACE-WITH-SECURE-RANDOM-PASSPHRASE"
  adminPassword: "shopware"
  serviceAccountName: "photodirect-pod"

persistence:
  accessMode: ReadWriteMany
  size: 30Gi
  storageClass: nfs

mariadb:
  enabled: false

externalDatabase:
  host: localhost
  user: shopware
  password: ""
  database: shopware
  port: 3306

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt
    cert-manager.io/cluster-issuer: letsencrypt
  hosts:
    - shopware.local
  path: /
